### ISSUE TITLE
Spelling mistake in splashes.txt

### ISSUE THREAD

**Issue by BraqueDown** [Encore-Developers/Encore#16]
Windows 10 x64, 03c1ca0 x64
https://github.com/Encore-Developers/Encore/blob/ef25aa42a918a3bcaa05c08b66157b36bd1f3bad/Encore/Assets/ui/splashes.txt#L10

The canon spelling is "phoenix".

![image](https://github.com/Encore-Developers/Encore/assets/43602802/78eb083b-efa4-4e28-a337-c8a3ec6c2429)

**Comment by NarrikSynthfox** [comment]
fixed
