### ISSUE TITLE
[BUG] [NIGHTLY] Fullscreen blocks windows from opening on top of it

### ISSUE THREAD

**Issue by Crafty-The-Fox** [Encore-Developers/Encore#41]
**Describe the bug**
Normally, you can open windows ontop of any window that is fullscreen, even in exclusive full screen, or it will swap back to the desktop if you alt tab.

**To Reproduce**
1. set to full screen
2. open file explorer or another window/try to alt tab to a window to make it appear

**Expected behavior**
window should pop up 

**System Info (please complete the following information):**
Windows 10

**Comment by 3drosalia** [comment]
i will most definitely look at this in a bit
i've had to semi-jerry rig together something to make fullscreen work properly, and ive been meaning to redo it just to make it work better on both linux and, now, fix this issue
ty for reporting!

**Comment by 3drosalia** [comment]
Seems like this was an issue with Raylib's fullscreen/borderless fullscreen functions. Will be fixed in the next commit.
![image](https://github.com/user-attachments/assets/a60b905f-5aa8-45f8-89a2-121c21069e8e)

**Comment by 3drosalia** [comment]
Fixed in commit [db30a1b](https://github.com/Encore-Developers/Encore/commit/db30a1bc27a6d512dd4a16a30a76fb20bb907f42)
