### ISSUE TITLE
[BUG] Multiplier clipped out if aspect ratio too tight

### ISSUE THREAD

**Issue by tposejank** [Encore-Developers/Encore#44]
**Describe the bug**
The score multiplier that appears on the screen at the far right is clipped out if the aspect ratio of the window is too tight

**To Reproduce**
1. Resize window while in gameplay
2. See

**Expected behavior**
Not cropped out

**Screenshots**
Unexpected
![image](https://github.com/user-attachments/assets/ce15d3fd-add9-4ced-aa99-68833de7254d)

Expected
![image](https://github.com/user-attachments/assets/d2bb96ca-bdb9-47dc-bc2b-83717e22868d)

Closeup
![image](https://github.com/user-attachments/assets/94e6571c-bab9-46d1-ba42-269750cb48d4)

**System Info (please complete the following information):**
 - OS: Windows (x64)
 - Version: 11, 23H2 22631.4169
 
**Tested also on**
 - OS: Linux Mint 22 Cinnamon (x64)
 - Version: 6.2.9

**Additional context**
Happens in almost every build with the multiplier up there

**Comment by 3drosalia** [comment]
solved in recent commits

**Comment by tposejank** [comment]
peak
