### ISSUE TITLE
[BUG] New Indev Build comes without players.json

### ISSUE THREAD

**Issue by WowItsOnlyConnor** [Encore-Developers/Encore#49]
**Describe the bug**
The most recent Indev Build doesn't have a players.json, meaning it crashes unless you have a json.

**To Reproduce**
1. Download the indev build
2. Open the game
3. Crash

**Expected behavior**
The game to load into the main menu

**System Info (please complete the following information):**
 - OS: Windows 10
 - Version: v0.2.0-indev:69af447

**Additional context**
Adding a players.json from older builds fixes this.

**Comment by 3drosalia** [comment]
Just noticed the discrepancy between Indev build.yml and Main build.yml. Thanks for reporting! closed in 669a4f0
