### ISSUE TITLE
[BUG] Game Crashes when attempting to load a song

### ISSUE THREAD

**Issue by WowItsOnlyConnor** [Encore-Developers/Encore#50]
**Describe the bug**
When I load a song, the game crashes.

**To Reproduce**
1. Attempt to load a song
2. Crash

**Expected behavior**
The song loads.

**Screenshots**
https://streamable.com/27lxf4

**System Info (please complete the following information):**
 - OS: Windows 10
 - Version:  v0.2.0-indev:4cfb0e6

**Additional context**
seemingly happens in more recent builds

**Comment by 3drosalia** [comment]
i wonder if you're missing any assets. it seems that, for some reason, whenever people download the game, it doesnt have all the necessary assets to play and crashes

**Comment by WowItsOnlyConnor** [comment]
At a glance, all of the assets appear in the files

**Comment by 3drosalia** [comment]
Does assets/gameplay/highway exist?

**Comment by WowItsOnlyConnor** [comment]
![image](https://github.com/user-attachments/assets/59da70fd-8cc4-4a27-a779-3c2abf6dc37a)
yes

**Comment by 3drosalia** [comment]
Could you potentially send me the chart you were trying out? Discord is probably preferred. I cant seem to recreate this on my own system with the songs I have
