### ISSUE TITLE
[BUG] Playing any song with any of the 3 player names makes it autoplay.

### ISSUE THREAD

**Issue by Mechaclank** [Encore-Developers/Encore#51]
**Describe the bug**
A clear and concise description of what the bug is, and the intended behaviour

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. We'd highly recommend sharing a video of said behavior, so that we can reproduce easier.

**System Info (please complete the following information):**
 - OS: [e.g. Windows, Linux (Arch/SteamOS), MacOS 13 Ventura]
 - Version: [e.g. v0.2.0-6319091]

**Additional context**

**Comment by 3drosalia** [comment]
hi could you elaborate on this issue?

**Comment by Mechaclank** [comment]
NVM, I found the solution. I had to download notepad++ and disable bot play
which is autoplay

**Comment by 3drosalia** [comment]
you can also do this in the overshell in recent commits, nice to see you solved it though
