### ISSUE TITLE
[BUG] Year and Charter doesn't appear on the song startup

### ISSUE THREAD

**Issue by WowItsOnlyConnor** [Encore-Developers/Encore#52]
**Describe the bug**
Whenever the song's info pops in for a few seconds, it does not show the year or the charter, unlike everyone else seemingly

**To Reproduce**
1. Enter a song
2. See `{Song Name], 0, Unknown Charter`

**Expected behavior**
Displays the year and charter of a song

**Screenshots**
![image](https://github.com/user-attachments/assets/027d0cea-e6f7-495b-9041-4396d4980924)

**System Info (please complete the following information):**
 - OS: Windows 10
 - Version: latest action build

**Additional context**

**Comment by WowItsOnlyConnor** [comment]
![image](https://github.com/user-attachments/assets/30678f27-ea3b-4b61-b6dc-671a69055b8b)

**Comment by 3drosalia** [comment]
As for the charter display not working: I'm not sure.

For "release_year", your issue is that it is a string when it should be a plain int.
`"release_year": 2024,` is appropriate

**Comment by NarrikSynthfox** [comment]
Fixed charter display in [7a3b2f5](https://github.com/Encore-Developers/Encore/commit/7a3b2f51b48329bb824e490c25d36a92019bf179), now it should work. Also, it doesn't need to be an array anymore, it can just be a single string if there's only one charter, and can be either "charter" or "charters"
