### ISSUE TITLE
[BUG] Overdrive doesn't stack (on pad atleast)

### ISSUE THREAD

**Issue by WowItsOnlyConnor** [Encore-Developers/Encore#56]
**Describe the bug**
Having overdrive active and hitting a phrase with it active doesn't grant more overdrive
**To Reproduce**
1. Activate overdrive
2. Complete a overdrive phrase while having overdrive active
3. No bonus overdrive

**Expected behavior**
You stack overdrive

**Screenshots**
[kinda lazy sorry, if you really need it ill record it if requested]

**System Info (please complete the following information):**
 - OS: Windows 10
 - Version: Indev actions... you know the drill atp

**Comment by 3drosalia** [comment]
fixed in [bee5e97](https://github.com/Encore-Developers/Encore/commit/bee5e97250c967b2c2477e5a42dc8a4846760124)
